# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cisco.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cisco.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63isco.proto\x1a google/protobuf/descriptor.proto\"*\n\x13\x43iscoMessageOptions\x12\x13\n\x0bschema_path\x18\x01 \x01(\t\"7\n\x11\x43iscoFieldOptions\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cpath_element\x18\x02 \x01(\t\"$\n\x10\x43iscoFileOptions\x12\x10\n\x08metadata\x18\x01 \x01(\t:J\n\tcisco_msg\x12\x1f.google.protobuf.MessageOptions\x18\xfb\xe2\x01 \x01(\x0b\x32\x14.CiscoMessageOptions:H\n\x0b\x63isco_field\x12\x1d.google.protobuf.FieldOptions\x18\xfc\xe2\x01 \x01(\x0b\x32\x12.CiscoFieldOptions:E\n\ncisco_file\x12\x1c.google.protobuf.FileOptions\x18\xfd\xe2\x01 \x01(\x0b\x32\x11.CiscoFileOptions')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


CISCO_MSG_FIELD_NUMBER = 29051
cisco_msg = _descriptor.FieldDescriptor(
  name='cisco_msg', full_name='cisco_msg', index=0,
  number=29051, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
CISCO_FIELD_FIELD_NUMBER = 29052
cisco_field = _descriptor.FieldDescriptor(
  name='cisco_field', full_name='cisco_field', index=1,
  number=29052, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
CISCO_FILE_FIELD_NUMBER = 29053
cisco_file = _descriptor.FieldDescriptor(
  name='cisco_file', full_name='cisco_file', index=2,
  number=29053, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_CISCOMESSAGEOPTIONS = _descriptor.Descriptor(
  name='CiscoMessageOptions',
  full_name='CiscoMessageOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema_path', full_name='CiscoMessageOptions.schema_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=91,
)


_CISCOFIELDOPTIONS = _descriptor.Descriptor(
  name='CiscoFieldOptions',
  full_name='CiscoFieldOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CiscoFieldOptions.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path_element', full_name='CiscoFieldOptions.path_element', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=148,
)


_CISCOFILEOPTIONS = _descriptor.Descriptor(
  name='CiscoFileOptions',
  full_name='CiscoFileOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='CiscoFileOptions.metadata', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['CiscoMessageOptions'] = _CISCOMESSAGEOPTIONS
DESCRIPTOR.message_types_by_name['CiscoFieldOptions'] = _CISCOFIELDOPTIONS
DESCRIPTOR.message_types_by_name['CiscoFileOptions'] = _CISCOFILEOPTIONS
DESCRIPTOR.extensions_by_name['cisco_msg'] = cisco_msg
DESCRIPTOR.extensions_by_name['cisco_field'] = cisco_field
DESCRIPTOR.extensions_by_name['cisco_file'] = cisco_file
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CiscoMessageOptions = _reflection.GeneratedProtocolMessageType('CiscoMessageOptions', (_message.Message,), dict(
  DESCRIPTOR = _CISCOMESSAGEOPTIONS,
  __module__ = 'cisco_pb2'
  # @@protoc_insertion_point(class_scope:CiscoMessageOptions)
  ))
_sym_db.RegisterMessage(CiscoMessageOptions)

CiscoFieldOptions = _reflection.GeneratedProtocolMessageType('CiscoFieldOptions', (_message.Message,), dict(
  DESCRIPTOR = _CISCOFIELDOPTIONS,
  __module__ = 'cisco_pb2'
  # @@protoc_insertion_point(class_scope:CiscoFieldOptions)
  ))
_sym_db.RegisterMessage(CiscoFieldOptions)

CiscoFileOptions = _reflection.GeneratedProtocolMessageType('CiscoFileOptions', (_message.Message,), dict(
  DESCRIPTOR = _CISCOFILEOPTIONS,
  __module__ = 'cisco_pb2'
  # @@protoc_insertion_point(class_scope:CiscoFileOptions)
  ))
_sym_db.RegisterMessage(CiscoFileOptions)

cisco_msg.message_type = _CISCOMESSAGEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(cisco_msg)
cisco_field.message_type = _CISCOFIELDOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(cisco_field)
cisco_file.message_type = _CISCOFILEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(cisco_file)

# @@protoc_insertion_point(module_scope)
