# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uptime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uptime.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cuptime.proto\"1\n\rsystem_uptime\x12\x10\n\x08hostname\x18\x32 \x01(\t\x12\x0e\n\x06uptime\x18\x33 \x01(\r')
)




_SYSTEM_UPTIME = _descriptor.Descriptor(
  name='system_uptime',
  full_name='system_uptime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='system_uptime.hostname', index=0,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='system_uptime.uptime', index=1,
      number=51, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['system_uptime'] = _SYSTEM_UPTIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

system_uptime = _reflection.GeneratedProtocolMessageType('system_uptime', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM_UPTIME,
  __module__ = 'uptime_pb2'
  # @@protoc_insertion_point(class_scope:system_uptime)
  ))
_sym_db.RegisterMessage(system_uptime)


# @@protoc_insertion_point(module_scope)
